name: Build and Archive

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-archive:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'  # specify the Go version you are using

      # Run the Makefile to build binaries for multiple environments
      - name: Run Makefile
        run: make

      # Archive the build folder
      - name: Archive build folder
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
